### ISSUE TITLE
Cannot modify application command in v3.0.0

### ISSUE THREAD

**Issue by Rutherther** [Discord-Net-Labs/Discord.Net-Labs#118]
Application commands cannot be modified in v3.0.0 by using `ModifyAsync` of `RestGuildCommand` or `RestGlobalCommand`.
The reason for that is that `InteractionHelper.ModifyGlobalCommand<ApplicationCommandProperties>` is called with abstract class generic argument and then instance is being created using activator of this class...

```
      System.MissingMethodException: Cannot create an abstract class.
         at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
         at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
         at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
         at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
         at System.Activator.CreateInstance(Type type)
         at Discord.Rest.InteractionHelper.ModifyGuildCommand[TArg](BaseDiscordClient client, IApplicationCommand command, UInt64 guildId, Action`1 func, RequestOptions options)
         at Discord.Rest.RestGuildCommand.ModifyAsync(Action`1 func, RequestOptions options)
```

**Comment by Rutherther** [comment]
I am thinking the easiest solution to fix this would be to make `RestGuildCommand.ModifyAsync` and `RestGlobalCommand.ModifyAsync` generic, but that would mean the user could specify wrong type here.

Better solution (non-breakable by user of the library) could be making `ModifyAsync` **protected(( and generic and then make classes like so:
```
RestSlashGuildCommand : RestGuildCommand
RestUserGuildCommand : RestGuildCommand
RestMessageGuildCommand : RestGuildCommand

RestSlashGlobalCommand : RestGlobalCommand
RestUserGlobalCommand : RestGlobalCommand
RestMessageGlobalCommand : RestGlobalCommand
```

and each one of these would specify `ModifyAsync` with the correct types.
The problem is that this adds a lot of classes which may not be desired.

Does anyone have better idea?

**Comment by Rutherther** [comment]
Or what about adding

```cs
public interface IModifyApplicationCommand<T>
  where T : ApplicationCommandProperties
{
  public Task ModifyAsync<T>(Action<T> func, RequestOptions options = null);
}

public interface ISlashCommand : IModifyApplicationCommand<SlashCommandProperties> {}
public interface IUserCommand : IModifyApplicationCommand<UserCommandProperties> {}
public interface IMessageCommand : IModifyApplicationCommand<MessageCommandProperties> {}
```

```cs
RestSlashGuildCommand : RestGuildCommand, ISlashCommand
RestUserGuildCommand : RestGuildCommand, IUserCommand
RestMessageGuildCommand : RestGuildCommand, IMessageCommand

RestSlashGlobalCommand : RestGlobalCommand, ISlashCommand
RestUserGlobalCommand : RestGlobalCommand, IUserCommand
RestMessageGlobalCommand : RestGlobalCommand, IMessageCommand
```

then modification could be done using cast to one of `ISlashCommand`, `IUserCommand`, `IMessageCommand`

**Comment by Rutherther** [comment]
Also note that `Activator.CreateInstance` cannot call internal constructors by default without correct flags and that it is slow. So I think it will be better to not use it and do something like switch and create new instances in it.
