### ISSUE TITLE
Exception on update async with SocketInteraction

### ISSUE THREAD

**Issue by JaJamyG** [Discord-Net-Labs/Discord.Net-Labs#135]
Getting an error when I click a button with the interactive buttons/dropdown eventhandler. Apparently it's something with the **UpdateAsync** method.

```
A InteractionCreated handler has thrown an unhandled exception.:
Discord.Net.HttpException: The server responded with error 10062: Unknown interaction
   at Discord.Net.Queue.RequestBucket.SendAsync(RestRequest request)
   at Discord.Net.Queue.RequestQueue.SendAsync(RestRequest request)
   at Discord.API.DiscordRestApiClient.SendInternalAsync(String method, String endpoint, RestRequest request)
   at Discord.API.DiscordRestApiClient.SendJsonAsync[TResponse](String method, String endpoint, Object payload, BucketId bucketId, ClientBucketType clientBucket, RequestOptions options)
   at Discord.API.DiscordRestApiClient.CreateInteractionResponse(InteractionResponse response, UInt64 interactionId, String interactionToken, RequestOptions options)
   at Discord.WebSocket.SocketMessageComponent.UpdateAsync(Action`1 func, RequestOptions options)
   at IntroDiscordLabs.Services.InteractionHandler.MyMessageComponentHandler(SocketMessageComponent interaction) in C:\Users\jamyv\source\repos\IntroDiscordLabs\IntroDiscordLabs\Services\InteractionHandler.cs:line 25
   at IntroDiscordLabs.Program.Client_InteractionCreated(SocketInteraction interaction) in C:\Users\jamyv\source\repos\IntroDiscordLabs\IntroDiscordLabs\Program.cs:line 69
   at Discord.EventExtensions.InvokeAsync[T](AsyncEvent`1 eventHandler, T arg)
   at Discord.WebSocket.DiscordSocketClient.TimeoutWrap(String name, Func`1 action)
```

**Comment by quinchs** [comment]
Could you verify that your not running 2 instances of a bot

**Comment by quinchs** [comment]
This exception happens when an app tries to send an initial response to an interaction twice. This can be caused by:
- 2 instances of your app running at once
- Using `RespondAsync` multiple times with `AlwaysAcknowledge` set to false

**Comment by JaJamyG** [comment]
> Could you verify that your not running 2 instances of a bot

No i'm working alone on my bots and it was only running on my pc.

**Comment by MrCakeSlayer** [comment]
Could you share what you have `AlwaysAcknowledge` set to and how your responding to the particular interaction that's throwing the error?
