### ISSUE TITLE
ArgumentNullException when trying to update a message after interaction with AlwaysAcknowledgeInteractions to false

### ISSUE THREAD

**Issue by NexganGH** [Discord-Net-Labs/Discord.Net-Labs#14]
With `AlwaysAcknowledgeInteractions` set to false (as suggested in the Readme file), I'm trying to update the original message of the interaction. After casting the `interaction `to `SocketMessageComponent`:

`await interaction.RespondAsync("test", type: InteractionResponseType.UpdateMessage);`

I get the following exception:
```
System.ArgumentNullException: Value cannot be null. (Parameter 'key')
at System.ThrowHelper.ThrowArgumentNullException(String name)
at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
at Discord.Net.Queue.RequestQueue.GetOrCreateBucket(RequestOptions options, IRequest request)
at Discord.Net.Queue.RequestQueue.SendAsync(RestRequest request)
at Discord.API.DiscordRestApiClient.SendInternalAsync(String method, String endpoint, RestRequest request)
at Discord.API.DiscordRestApiClient.SendAsync[TResponse](String method, String endpoint, BucketId bucketId, ClientBucketType clientBucket, RequestOptions options)
at Discord.API.DiscordRestApiClient.GetInteractionResponse(String interactionToken, RequestOptions options)
at Discord.Rest.InteractionHelper.SendInteractionResponse(BaseDiscordClient client, IMessageChannel channel, InteractionResponse response, UInt64 interactionId, String interactionToken, RequestOptions options)
at Discord.WebSocket.SocketMessageComponent.RespondAsync(String text, Boolean isTTS, Embed embed, InteractionResponseType type, Boolean ephemeral, AllowedMentions allowedMentions, RequestOptions options, MessageComponent component)
at EmpyManager.Bot.Modules.TemporaryChannels.UserOwnedChannel.PerformActionAsync(String action, SocketMessageComponent interaction) in C:\Users\Torto\source\repos\EmpyManager\Bot\Modules\TemporaryChannels\EmpyManager.Bot.Modules.TemporaryChannels\Entities\UserOwnedChannel.Text.cs:line 127
```

**Comment by quinchs** [comment]
Update Discord .Net Labs version to 2.3.6

**Comment by NexganGH** [comment]
Seems to be working with the new update. Thanks!
