### ISSUE TITLE
Rate Limit Triggered with ModifyAsync() then Timed out

### ISSUE THREAD

**Issue by Raviiiing** [Discord-Net-Labs/Discord.Net-Labs#143]
Hello, I have 3 buttons 2 that use a ModifyAsync() and one that use DeleteAsync() (for text channels) if i press 3 times in a row a ModifyAsync Button i get this error : 

```
20:54:40 Discord     Discord.Net v3.0.0 (API v9)
20:54:41 Gateway     Connecting
20:54:42 Gateway     Connected
20:54:43 Gateway     Ready
20:55:19 Rest        Rate limit triggered: PATCH channels/885961557870252044 (Bucket: 9852e1a53c06ffc5a89d65fef85ca4ce)
20:55:19 Rest        Rate limit triggered: PATCH channels/885961557870252044 (Bucket: 9852e1a53c06ffc5a89d65fef85ca4ce)
20:55:19 Rest        Rate limit triggered: PATCH channels/885961557870252044 (Bucket: 9852e1a53c06ffc5a89d65fef85ca4ce)
20:55:19 Rest        Rate limit triggered: PATCH channels/885961557870252044 (Bucket: 9852e1a53c06ffc5a89d65fef85ca4ce)
20:55:19 Rest        Rate limit triggered: PATCH channels/885961557870252044 (Bucket: 9852e1a53c06ffc5a89d65fef85ca4ce)
20:55:19 Rest        Rate limit triggered: PATCH channels/885961557870252044 (Bucket: 9852e1a53c06ffc5a89d65fef85ca4ce)
20:55:20 Rest        Rate limit triggered: PATCH channels/885961557870252044 (Bucket: 9852e1a53c06ffc5a89d65fef85ca4ce)
20:55:20 Rest        Rate limit triggered: PATCH channels/885961557870252044 (Bucket: 9852e1a53c06ffc5a89d65fef85ca4ce)
20:55:21 Gateway     A ButtonExecuted handler is blocking the gateway task.
20:55:29 Rest        Rate limit triggered: PATCH channels/885961557870252044 (Bucket: 9852e1a53c06ffc5a89d65fef85ca4ce)
20:55:30 Rest        Rate limit triggered: PATCH channels/885961557870252044 (Bucket: 9852e1a53c06ffc5a89d65fef85ca4ce)
20:55:30 Rest        Rate limit triggered: PATCH channels/885961557870252044 (Bucket: 9852e1a53c06ffc5a89d65fef85ca4ce)
20:55:30 Rest        Rate limit triggered: PATCH channels/885961557870252044 (Bucket: 9852e1a53c06ffc5a89d65fef85ca4ce)
20:55:30 Rest        Rate limit triggered: PATCH channels/885961557870252044 (Bucket: 9852e1a53c06ffc5a89d65fef85ca4ce)
20:55:30 Rest        Rate limit triggered: PATCH channels/885961557870252044 (Bucket: 9852e1a53c06ffc5a89d65fef85ca4ce)
20:55:30 Rest        Rate limit triggered: PATCH channels/885961557870252044 (Bucket: 9852e1a53c06ffc5a89d65fef85ca4ce)
20:55:31 Rest        Rate limit triggered: PATCH channels/885961557870252044 (Bucket: 9852e1a53c06ffc5a89d65fef85ca4ce)
20:55:31 Rest        Rate limit triggered: PATCH channels/885961557870252044 (Bucket: 9852e1a53c06ffc5a89d65fef85ca4ce)
20:55:31 Rest        Rate limit triggered: PATCH channels/885961557870252044 (Bucket: 9852e1a53c06ffc5a89d65fef85ca4ce)
20:55:32 Rest        Rate limit triggered: PATCH channels/885961557870252044 (Bucket: 9852e1a53c06ffc5a89d65fef85ca4ce)
20:55:32 Rest        Rate limit triggered: PATCH channels/885961557870252044 (Bucket: 9852e1a53c06ffc5a89d65fef85ca4ce)
20:55:32 Rest        Rate limit triggered: PATCH channels/885961557870252044 (Bucket: 9852e1a53c06ffc5a89d65fef85ca4ce)
20:55:32 Rest        Rate limit triggered: PATCH channels/885961557870252044 (Bucket: 9852e1a53c06ffc5a89d65fef85ca4ce)
20:55:32 Rest        Rate limit triggered: PATCH channels/885961557870252044 (Bucket: 9852e1a53c06ffc5a89d65fef85ca4ce)
20:55:32 Rest        Rate limit triggered: PATCH channels/885961557870252044 (Bucket: 9852e1a53c06ffc5a89d65fef85ca4ce)
20:55:33 Rest        Rate limit triggered: PATCH channels/885961557870252044 (Bucket: 9852e1a53c06ffc5a89d65fef85ca4ce)
20:55:33 Rest        Rate limit triggered: PATCH channels/885961557870252044 (Bucket: 9852e1a53c06ffc5a89d65fef85ca4ce)
20:55:33 Rest        Rate limit triggered: PATCH channels/885961557870252044 (Bucket: 9852e1a53c06ffc5a89d65fef85ca4ce)
20:55:33 Rest        Rate limit triggered: PATCH channels/885961557870252044 (Bucket: 9852e1a53c06ffc5a89d65fef85ca4ce)
20:55:33 Rest        Rate limit triggered: PATCH channels/885961557870252044 (Bucket: 9852e1a53c06ffc5a89d65fef85ca4ce)
20:55:33 Rest        Rate limit triggered: PATCH channels/885961557870252044 (Bucket: 9852e1a53c06ffc5a89d65fef85ca4ce)
20:55:33 Rest        Rate limit triggered: PATCH channels/885961557870252044 (Bucket: 9852e1a53c06ffc5a89d65fef85ca4ce)
20:55:34 Gateway     A ButtonExecuted handler has thrown an unhandled exception.:
System.TimeoutException: The operation has timed out.
   at Discord.Net.Queue.RequestBucket.EnterAsync(Int32 id, IRequest request)
   at Discord.Net.Queue.RequestBucket.SendAsync(RestRequest request)
   at Discord.Net.Queue.RequestQueue.SendAsync(RestRequest request)
   at Discord.API.DiscordRestApiClient.SendInternalAsync(String method, String endpoint, RestRequest request)
   at Discord.API.DiscordRestApiClient.SendJsonAsync[TResponse](String method, String endpoint, Object payload, BucketId bucketId, ClientBucketType clientBucket, RequestOptions options)
   at Discord.API.DiscordRestApiClient.ModifyGuildChannelAsync(UInt64 channelId, ModifyTextChannelParams args, RequestOptions options)
   at Discord.Rest.ChannelHelper.ModifyAsync(ITextChannel channel, BaseDiscordClient client, Action`1 func, RequestOptions options)
   at AOG_BOT.Program.MyButtonHandler(SocketMessageComponent component) in C:\Users\yanna\OneDrive\Projet Perso\AOG_BOT\Program.cs:line 165
   at Discord.EventExtensions.InvokeAsync[T](AsyncEvent`1 eventHandler, T arg)
   at Discord.WebSocket.DiscordSocketClient.TimeoutWrap(String name, Func`1 action)
```
And here is my code for handling buttons : 

```
public async Task MyButtonHandler(SocketMessageComponent component) 
        {
            SocketGuild guild = _client.GetGuild(850182424271912961);
            SocketGuildUser user = guild.GetUser(component.User.Id);

            if (user.GuildPermissions.Administrator)
            {
                switch (component.Data.CustomId)
                {

                    case "close":
                        {
                            ITextChannel textChannel = guild.GetTextChannel(component.Channel.Id);
                            if (textChannel.Name.StartsWith($"🔒"))
                            {
                                string name = textChannel.Name.Substring(1, textChannel.Name.Length - 2); ;
                                string newName = name.Substring(1, name.Length - 2);
                                await textChannel.SendMessageAsync($"{component.User.Mention} a ré-ouvert le ticket !");
                                await Task.Delay(500);
                                await textChannel.ModifyAsync(prop => prop.Name = $"{newName}");
                            }
                            else
                            {
                                string name = textChannel.Name;
                                await textChannel.SendMessageAsync($"🔒 {component.User.Mention} a fermé le ticket ! 🔒");
                                await Task.Delay(500);
                                await textChannel.ModifyAsync(prop => prop.Name = $"🔒 {name} 🔒");
                            }
                        }
                        break;
                    case "delete":
                        {
                            ITextChannel textChannel = guild.GetTextChannel(component.Channel.Id);
                            await textChannel.DeleteAsync();
                        }
                        break;
                    case "critical":
                        {
                            ITextChannel textChannel = guild.GetTextChannel(component.Channel.Id);
                            if(textChannel.Name.StartsWith($"⚠️"))
                            {
                                string name = textChannel.Name.Substring(1, textChannel.Name.Length - 2); ;
                                string newName = name.Substring(1, name.Length - 2);
                                await textChannel.SendMessageAsync($"{component.User.Mention} a changé le statut à normal !");
                                await textChannel.ModifyAsync(prop => prop.Name = $"{newName}");
                            }
                            else
                            {
                                string name = textChannel.Name;
                                await textChannel.SendMessageAsync($"⚠️ {component.User.Mention} a changé le statut à critique ! ⚠️");
                                await textChannel.ModifyAsync(prop => prop.Name = $"⚠️ {name} ⚠️"); //Line 165
                            }
                        }
                        break;
                }
            }else
            {
                await component.RespondAsync("Vous n'êtes pas administrateur Impossible de faire ça!", ephemeral: true);
            }
        }
```
Note: DeleteAsync() seems to work fine.

I can provide more things if asked.
Thanks

**Comment by drobbins329** [comment]
3 times in rapid succession for the modify buttons, is actually 6 api calls. depending on your pings, the 500ms delay may not count for much. The delete works better because it's a one-shot deal.

**Comment by Raviiiing** [comment]
> 3 times in rapid succession for the modify buttons, is actually 6 api calls. depending on your pings, the 500ms delay may not count for much. The delete works better because it's a one-shot deal.

The problem is i don't press them in rapid succession, whatever the time i wait the 3rd one will cause this exception

**Comment by drobbins329** [comment]
> > 3 times in rapid succession for the modify buttons, is actually 6 api calls. depending on your pings, the 500ms delay may not count for much. The delete works better because it's a one-shot deal.
> 
> 
> 
> The problem is i don't press them in rapid succession, whatever the time i wait the 3rd one will cause this exception

Can you join us on the D.Net labs discord at https://discord.gg/7NTUNG3f ? We can discuss and troubleshoot a little easier there.

**Comment by Raviiiing** [comment]
So, it's because i'm making too much API calls (2call evry 10mins) so it's normal to have this exception
