### ISSUE TITLE
Hyperlink buttons raise a bad request error

### ISSUE THREAD

**Issue by rikashore** [Discord-Net-Labs/Discord.Net-Labs#2]
Using this code 
```cs
        [Command("button")]
        public async Task ButtonAsync()
        {
            var builder = new ComponentBuilder().WithButton("Hello!", ButtonStyle.Link, emote: null, customId: "hello_button",
                url: "https://github.com/shift-eleven/Alexandra", disabled: false, row: 0);

            await Context.Channel.SendMessageAsync("Buttons!", component: builder.Build());
        }
```

Upon attempting to send them to a channel, Im getting a bad request error

```
 Discord.Commands.CommandService[0]
      Command:
      Discord.Commands.CommandException: Error occurred executing "button" for shift-eleven#7304 in Black Rose/bot-test.
       ---> Discord.Net.HttpException: The server responded with error 400: BadRequest
         at Discord.Net.Queue.RequestBucket.SendAsync(RestRequest request)
         at Discord.Net.Queue.RequestQueue.SendAsync(RestRequest request)
         at Discord.API.DiscordRestApiClient.SendInternalAsync(String method, String endpoint, RestRequest request)
         at Discord.API.DiscordRestApiClient.SendJsonAsync[TResponse](String method, String endpoint, Object payload, BucketId bucketId, ClientBucketType clientBucket, RequestOptions options)
         at Discord.API.DiscordRestApiClient.CreateMessageAsync(UInt64 channelId, CreateMessageParams args, RequestOptions options)
         at Discord.Rest.ChannelHelper.SendMessageAsync(IMessageChannel channel, BaseDiscordClient client, String text, Boolean isTTS, Embed embed, AllowedMentions allowedMentions, MessageReference messageReference, MessageCo
mponent component, RequestOptions options)
         at Harley.Modules.GeneralModule.ButtonAsync() in D:\Projects\C# projects\Harley\Harley\Modules\GeneralModule.cs:line 21
         at Discord.Commands.ModuleClassBuilder.<>c__DisplayClass6_0.<<BuildCommand>g__ExecuteCallback|0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Discord.Commands.CommandInfo.ExecuteInternalAsync(ICommandContext context, Object[] args, IServiceProvider services)
         --- End of inner exception stack trace ---
dbug: Discord.WebSocket.DiscordSocketClient[0]
      Rest: POST channels/825360796153544735/messages: 507.73 ms

```
Full Stack trace

It is noted that the example in the readme works as intended, alongside with the event handler

**Comment by quinchs** [comment]
The issue lies within this part of the docs
- Non-link buttons must have a `custom_id`, and cannot have a `url`
- Link buttons must have a `url`, and cannot have a `custom_id`
- Link buttons do not send an interaction to your app when clicked

I will add a check to the builder when adding buttons for this. For now just dont pass in a custom Id

**Comment by rikashore** [comment]
Alright, thanks for clarifying this
