### ISSUE TITLE
Exception when responding to interaction with ephemeral true

### ISSUE THREAD

**Issue by turulix** [Discord-Net-Labs/Discord.Net-Labs#20]
Using RespondAsync to respond to an Interaction using ephemeral true will cause this exception. AlwaysAcknowledgeInteractions is set to False

```
Discord.Net.HttpException: The server responded with error 10008: Unknown Message
   at Discord.Net.Queue.RequestBucket.SendAsync(RestRequest request)
   at Discord.Net.Queue.RequestQueue.SendAsync(RestRequest request)
   at Discord.API.DiscordRestApiClient.SendInternalAsync(String method, String endpoint, RestRequest request)
   at Discord.API.DiscordRestApiClient.SendAsync[TResponse](String method, String endpoint, BucketId bucketId, ClientBucketType clientBucket, RequestOptions options)
   at Discord.API.DiscordRestApiClient.GetInteractionResponse(String interactionToken, RequestOptions options)
   at Discord.Rest.InteractionHelper.SendInteractionResponse(BaseDiscordClient client, IMessageChannel channel, InteractionResponse response, UInt64 interactionId, String interactionToken, RequestOptions options)
   at Discord.WebSocket.SocketMessageComponent.RespondAsync(String text, Boolean isTTS, Embed embed, InteractionResponseType type, Boolean ephemeral, AllowedMentions allowedMentions, RequestOptions options, MessageComponent component)
   ```

**Comment by MrCakeSlayer** [comment]
I've also encountered this issue, though it appears to be guild-specific (at least in my case). As the commands that trigger it will work in most guilds but a select few will trigger it. (Maybe permission related?)

**Comment by quinchs** [comment]
Seems to be fixed in later versions
