### ISSUE TITLE
Calling StartAsync on a DiscordSocketClient more than once causes it to soft lock.

### ISSUE THREAD

**Issue by CottageDwellingCat** [Discord-Net-Labs/Discord.Net-Labs#271]
Calling StartAsync on a DiscordSocketClient causes it to stop responding to events and methods. The following code contains a reproducible example. (note the bot needs a slash command registered before running the example)
```cs
using Discord;
using System;
using Discord.WebSocket;
using System.Threading.Tasks;

namespace DnetTest
{
	class Program
	{
		internal const string Token = "your token here";
		public static async Task Main()
		{
			DiscordSocketClient client = new(new DiscordSocketConfig()
			{
				LogLevel = LogSeverity.Debug,
				DefaultRetryMode = RetryMode.AlwaysRetry
			});
			
			client.Log += x =>
			{
				Console.WriteLine(x);
				return Task.CompletedTask;
			};

			await client.LoginAsync(TokenType.Bot, Token);
			await client.StartAsync();
			
			client.SlashCommandExecuted += async (x) =>
			{
				Console.WriteLine("received command, stopping client");
				await client.StartAsync();
				await x.RespondAsync("stopped the client", ephemeral: true);
			};
			
			await Task.Delay(-1);
		}
	}
}
```

<details> <summary>Click to reveal log output</summary>
<p>
this is the output of running the sample

```
10:49:16 Discord     Discord.Net v3.1.7 (API v9)
10:49:16 Rest        GET sticker-packs: 447.88 ms
10:49:16 Gateway     Connecting
10:49:16 Gateway     Connecting ApiClient
10:49:16 Rest        GET gateway: 53.98 ms
10:49:17 Gateway     Received Hello
10:49:17 Gateway     Heartbeat Started
10:49:17 Gateway     Identifying
10:49:17 Gateway     Sent Heartbeat
10:49:17 Gateway     Sent Identify
10:49:17 Gateway     Received HeartbeatAck
10:49:17 Gateway     Latency = 78 ms
10:49:17 Gateway     Received Dispatch (READY)
10:49:17 Gateway     GuildDownloader Started
10:49:17 Gateway     Connected
10:49:17 Gateway     Raising Event
10:49:17 Gateway     Received Dispatch (GUILD_AVAILABLE)
10:49:17 Gateway     Connected to CottageDwellersCoven
10:49:17 Gateway     GuildDownloader Stopped
10:49:17 Gateway     Ready
10:49:24 Gateway     Received Dispatch (INTERACTION_CREATE)
received command, stopping client
10:49:24 Gateway     Heartbeat Stopped
10:49:24 Gateway     System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Discord.ConnectionManager.<>c__DisplayClass29_0.<<StartAsync>b__0>d.MoveNext()
10:49:24 Gateway     Failed to start the connection: System.Threading.Tasks.TaskCanceledException: A task was canceled.   at Discord.ConnectionManager.<>c__DisplayClass29_0.<<StartAsync>b__0>d.MoveNext():
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Discord.ConnectionManager.<>c__DisplayClass29_0.<<StartAsync>b__0>d.MoveNext()
10:49:24 Gateway     Disconnecting
10:49:24 Gateway     Disconnecting ApiClient
```
</p>
</details>
originally reported by Omi#9823 on Discord

**Comment by quinchs** [comment]
It looks like the client.StartAsync() call will disconnect the running client before trying to reconnect, should this be the intended behavior?  

And with the soft lock, does the client.StartAsync() method hang? or is it just no events?

**Comment by CottageDwellingCat** [comment]
The method hangs indefinitely + no events on the client. Calling other methods (tested on get channel and send message) while it is hanging works fine. It also looks like the client stops heat beating.

**Comment by CottageDwellingCat** [comment]
I think this could be resolved by just adding this to `ConnectionManager.StartAsync()`, I ran some tests and it did not seem to cause any issues; there shouldn't be any cases where this could cause an issue in users bots because calling the method when `State` was not `ConnectionState.Disconnected` would cause a soft lock.
```csharp
if (State != ConnectionState.Disconnected)
    throw new InvalidOperationException("Cannot start an already running client.");
```

**Comment by quinchs** [comment]
Go ahead and open a PR for this.
