### ISSUE TITLE
Parsing REST interactions throws exceptions

### ISSUE THREAD

**Issue by d4n3436** [Discord-Net-Labs/Discord.Net-Labs#294]
Using `ParseHttpInteractionAsync()` with different types of interactions throws exceptions.

Parsing a REST user command throws a `NullReferenceException`.
The same happens with slash commands with a `User` parameter.

![image](https://user-images.githubusercontent.com/39978852/142776848-2db57749-3c21-470b-9343-6ba2f49b2c1b.png)

```
System.NullReferenceException: Object reference not set to an instance of an object.
         at Discord.Rest.RestGuildUser.Create(BaseDiscordClient discord, IGuild guild, GuildMember model)
         at Discord.Rest.RestResolvableData`1.PopulateAsync(DiscordRestClient discord, IGuild guild, IRestMessageChannel channel, T model)
         at Discord.Rest.RestCommandBaseData`1.UpdateAsync(DiscordRestClient client, ApplicationCommandInteractionData model, IGuild guild, IRestMessageChannel channel)
         at Discord.Rest.RestCommandBaseData`1.CreateAsync(DiscordRestClient client, ApplicationCommandInteractionData model, IGuild guild, IRestMessageChannel channel)
         at Discord.Rest.RestCommandBase.UpdateAsync(DiscordRestClient client, Interaction model)
         at Discord.Rest.RestUserCommand.UpdateAsync(DiscordRestClient client, Interaction model)
         at Discord.Rest.RestUserCommand.CreateAsync(DiscordRestClient client, Interaction model)
         at Discord.Rest.RestInteraction.CreateAsync(DiscordRestClient client, Interaction model)
         at Discord.Rest.DiscordRestClient.ParseHttpInteractionAsync(String publicKey, String signature, String timestamp, Byte[] body)
```

Parsing a REST slash command with a `Channel` parameter throws an `InvalidOperationException`:

![image](https://user-images.githubusercontent.com/39978852/142777574-67c170c7-4ea4-4556-b02d-78bdea2444ad.png)

```
System.InvalidOperationException: This property has no value set.
         at Discord.Optional`1.get_Value()
         at Discord.Rest.RestChannel.Create(BaseDiscordClient discord, Channel model)
         at Discord.Rest.RestResolvableData`1.PopulateAsync(DiscordRestClient discord, IGuild guild, IRestMessageChannel channel, T model)
         at Discord.Rest.RestCommandBaseData`1.UpdateAsync(DiscordRestClient client, ApplicationCommandInteractionData model, IGuild guild, IRestMessageChannel channel)
         at Discord.Rest.RestCommandBaseData`1.CreateAsync(DiscordRestClient client, ApplicationCommandInteractionData model, IGuild guild, IRestMessageChannel channel)
         at Discord.Rest.RestCommandBase.UpdateAsync(DiscordRestClient client, Interaction model)
         at Discord.Rest.RestSlashCommand.UpdateAsync(DiscordRestClient client, Interaction model)
         at Discord.Rest.RestSlashCommand.CreateAsync(DiscordRestClient client, Interaction model)
         at Discord.Rest.RestInteraction.CreateAsync(DiscordRestClient client, Interaction model)
         at Discord.Rest.DiscordRestClient.ParseHttpInteractionAsync(String publicKey, String signature, String timestamp, Byte[] body)
```

I'm using a `DiscordRestClient` and a ASP.NET Core Web API to receive the interactions.
I thought REST interactions where ready to use 🤔

**Comment by quinchs** [comment]
For the slash command parameters the main reason is how the resolvable data works.
In the socket side the channels are pulled from cache then updated while on the rest side its created from the resolvable model. The issue is the model doesn't contain a guild id so it has to be set manually
