### ISSUE TITLE
Modifying a message specifing AllowedMentions and no embeds throws an InvalidOperationException

### ISSUE THREAD

**Issue by d4n3436** [Discord-Net-Labs/Discord.Net-Labs#300]
Modifying a message specifing `AllowedMentions` and no `Embeds` throws an `InvalidOperationException`.

```
System.InvalidOperationException: This property has no value set.
   at Discord.Optional`1.get_Value()
   at Discord.Rest.MessageHelper.ModifyAsync(UInt64 channelId, UInt64 msgId, BaseDiscordClient client, Action`1 func, RequestOptions options)
   at Discord.Rest.RestUserMessage.ModifyAsync(Action`1 func, RequestOptions options)
```
Example command:
```cs
[Command("test")]
public async Task Test()
{
    var msg = await ReplyAsync("test");

    await msg.ModifyAsync(x =>
    {
        x.Content = "edited message";
        x.AllowedMentions = AllowedMentions.None;
    });
}
```

It seems that commit fd28b61 introduced the bug (it worked in 3.1.7 but not in 3.2.0+)

**Comment by d4n3436** [comment]
It seems that a [squash commit](https://github.com/Discord-Net-Labs/Discord.Net-Labs/blame/821c9beae5edc0a973867629c68bc74d81ee86d8/src/Discord.Net.Rest/Entities/Messages/MessageHelper.cs#L54) reintroduced the bug lol, I'm getting this exception in version 3.4.7.
