### ISSUE TITLE
Weird issue with buttons

### ISSUE THREAD

**Issue by SylveonDeko** [Discord-Net-Labs/Discord.Net-Labs#61]
This morning i created buttons for my modules command, it worked perfectly fine until just now, it says this:
``
Discord.Net.HttpException: The server responded with error 50035: Invalid Form Body
   at Discord.Net.Queue.RequestBucket.SendAsync(RestRequest request)
   at Discord.Net.Queue.RequestQueue.SendAsync(RestRequest request)
   at Discord.API.DiscordRestApiClient.SendInternalAsync(String method, String endpoint, RestRequest request)
   at Discord.API.DiscordRestApiClient.SendJsonAsync[TResponse](String method, String endpoint, Object payload, BucketId bucketId, ClientBucketType clientBucket, RequestOptions options)
   at Discord.API.DiscordRestApiClient.CreateMessageAsync(UInt64 channelId, CreateMessageParams args, RequestOptions options)
   at Discord.Rest.ChannelHelper.SendMessageAsync(IMessageChannel channel, BaseDiscordClient client, String text, Boolean isTTS, Embed embed, AllowedMentions allowedMentions, MessageReference messageReference, MessageComponent component, RequestOptions options)
   at Discord.WebSocket.SocketTextChannel.Discord.IMessageChannel.SendMessageAsync(String text, Boolean isTTS, Embed embed, RequestOptions options, AllowedMentions allowedMentions, MessageReference messageReference, MessageComponent component)
   at Mewdeko.Modules.Help.Help.Commands(String module) in D:\Docs\Mewdeko\Mewdeko.Core\Modules\Help\Help.cs:line 307
   at Discord.Commands.ModuleClassBuilder.<>c__DisplayClass6_0.<<BuildCommand>g__ExecuteCallback|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Discord.Commands.CommandInfo.ExecuteInternalAsync(ICommandContext context, Object[] args, IServiceProvider services)
   at Discord.Commands.CommandInfo.ExecuteInternalAsync(ICommandContext context, Object[] args, IServiceProvider services)
   at Discord.Commands.CommandInfo.ExecuteInternalAsync(ICommandContext context, Object[] args, IServiceProvider services)
   at Discord.Commands.CommandInfo.ExecuteAsync(ICommandContext context, IEnumerable`1 argList, IEnumerable`1 paramList, IServiceProvider services)``

I havent changed my code at all whenthis happenned 
Button Code:
``var builder = new ComponentBuilder()
                .WithButton("Custom Reactions", customId: "customreactions", ButtonStyle.Primary, row: 0)
                .WithButton("Administration", customId: "administration", ButtonStyle.Primary, row: 0);
                ``

**Comment by INikonI** [comment]
I think problem in your other arguments, which you provide to send message method. I tried to send message with your buttons and its work fine.

**Comment by INikonI** [comment]
Can you provide more code?
