### ISSUE TITLE
Getting an issue when modifying embeds on the new commits after everything was renamed to EMbeds

### ISSUE THREAD

**Issue by SylveonDeko** [Discord-Net-Labs/Discord.Net-Labs#65]
```
System.MissingMethodException: Method not found: 'Discord.Optional`1<Discord.Embed> Discord.MessageProperties.get_Embed()'.
   at Discord.Rest.MessageHelper.ModifyAsync(IMessage msg, BaseDiscordClient client, Action`1 func, RequestOptions options)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Discord.Rest.MessageHelper.ModifyAsync(IMessage msg, BaseDiscordClient client, Action`1 func, RequestOptions options)
   at Discord.WebSocket.SocketUserMessage.ModifyAsync(Action`1 func, RequestOptions options)
   at Mewdeko.Modules.Help.Help.HandleModules(SocketInteraction ine) in D:\Docs\Mewdeko\Mewdeko.Core\Modules\Help\Help.cs:line 119
   at Discord.EventExtensions.InvokeAsync[T](AsyncEvent`1 eventHandler, T arg)
   at Discord.WebSocket.DiscordSocketClient.TimeoutWrap(String name, Func`1 action)
   ```

**Comment by INikonI** [comment]
Code? Its work fine for me, again, as well as your other issue.

**Comment by INikonI** [comment]
Maybe you need make changes like this
```diff
- Message.ModifyAsync(props => props.Embed = new EmbedBuilder(...).Build());
+ Message.ModifyAsync(props => props.Embeds = new[] { new EmbedBuilder(...).Build() });
```

**Comment by SylveonDeko** [comment]
thats exactly what i did
```
await msg.ModifyAsync(x => x.Embeds = new Embed[] { toSend.Build() }).ConfigureAwait(false);
```

**Comment by SylveonDeko** [comment]
i pulled from the latest commit, unless i didnt build everything i needed

**Comment by INikonI** [comment]
I pulled latest commit and build it, work fine again 🤔
